# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.4.6
      # Error: Database is uninitialized and superuser password is not specified.
      #  You must specify POSTGRES_PASSWORD to a non-empty value for the
      #  superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
      # - image: circleci/postgres:13
    working_directory: ~/repo
    steps:
      - checkout
